default:
  image: ruby:3.2.2

  before_script:
    - gem install test-unit rubygems-tasks steep
    - gem install rbs -v 3.4.0.pre.1

test:
  variables:
    RB_SYS_FORCE_INSTALL_RUST_TOOLCHAIN: 'true'
  script:
    - rake
