# TypeProf 0.21.8

# Classes
class Pathname
  def self.common_prefix: (*pathnamable paths) -> Pathname?
  def common_prefix: (*pathnamable others) -> Pathname?
  def start_with?: (pathnamable other) -> bool
end

type pathnamable = Array[pathnamable] | Pathname | string

# Class just for type checking
class NonEmptyArray[T] < Array[T]
  def pop: -> T
end
