# TypeProf 0.21.8

# Classes
class Pathname
  def self.common_prefix: (*Array[Array[_ToStr] | _ToStr] | Pathname | _ToStr paths) -> Pathname?
  def common_prefix: (*Array[Array[_ToStr] | Pathname | _ToStr] others) -> Pathname?
  def start_with?: (Pathname | _ToStr other) -> bool
end

# Class just for type checking
class NonEmptyArray[T] < Array[T]
  def pop: -> T
end
